#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
fibonacci=[1,2]
count_a=0
count_b=1
while (fibonacci[-1]<4000000):
    to_append=(fibonacci[count_a]+fibonacci[count_b])
    fibonacci.append(to_append)
    count_a=count_a+1
    count_b=count_b+1
del fibonacci[-1]
fibonacci_2=[]
for x in fibonacci:
    if (x%2)==0:
        fibonacci_2.append(x)

print(sum(fibonacci_2))