#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
#Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
#Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
#It can be verified that T285 = P165 = H143 = 40755.
#Find the next triangle number that is also pentagonal and hexagonal.
import time
start_time = time.clock()
def is_pentagonal(x):
    if ((1+(1+24*x)**0.5)/6).is_integer():
        return(True)
    else:
        return(False)

def is_triangle(x):
    if ((-1+(1+8*x)**0.5)/2).is_integer():
        return(True)
    else:
        return(False)

def is_hexagonal(x):
    if ((1+(1+8*x)**(0.5))/4).is_integer():
        return(True)
    else:
        return(False)

for x in range(200000):
    y=x*(2*x-1)
    if is_pentagonal(y)==True:
        if is_triangle(y)==True:
            print(y)

print(time.clock() - start_time, "seconds")