#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is
#minimised; what is the value of D?

def is_pentagonal(x):
    if ((1+(1+24*x)**0.5)/6).is_integer():
        return(True)
    else:
        return(False)
def pent():
    for x in range(1,10000):
        for y in range(1,10000):
            a=x*(3*x-1)*0.5
            b=y*(3*y-1)*0.5
            if (a-b)>0:
                if is_pentagonal(a-b)==True and is_pentagonal(a+b)==True:
                    return(abs(a-b))

print(pent())